<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.card/xml/schema/CRM/Card/Card.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:2224d9132d5995787b87717ed8ee7706)
 */
use CRM_Card_ExtensionUtil as E;

/**
 * Database access object for the Card entity.
 */
class CRM_Card_DAO_Card extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_card_mapping';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Card ID
   *
   * @var int
   */
  public $id;

  /**
   * Template ID
   *
   * @var int
   */
  public $template_id;

  /**
   * Entity Type
   *
   * @var string
   */
  public $entity_type;

  /**
   * Entity Type
   *
   * @var string
   */
  public $entity_mapping;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_card_mapping';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Cards') : E::ts('Card');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'template_id', 'civicrm_card_html', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Card ID'),
          'required' => TRUE,
          'where' => 'civicrm_card_mapping.id',
          'table_name' => 'civicrm_card_mapping',
          'entity' => 'Card',
          'bao' => 'CRM_Card_DAO_Card',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'template_id' => [
          'name' => 'template_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Template ID'),
          'required' => TRUE,
          'where' => 'civicrm_card_mapping.template_id',
          'table_name' => 'civicrm_card_mapping',
          'entity' => 'Card',
          'bao' => 'CRM_Card_DAO_Card',
          'localizable' => 0,
          'FKClassName' => 'CRM_Card_DAO_CardHtml',
          'add' => NULL,
        ],
        'entity_type' => [
          'name' => 'entity_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Type'),
          'description' => E::ts('Entity Type'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_card_mapping.entity_type',
          'table_name' => 'civicrm_card_mapping',
          'entity' => 'Card',
          'bao' => 'CRM_Card_DAO_Card',
          'localizable' => 0,
          'add' => NULL,
        ],
        'entity_mapping' => [
          'name' => 'entity_mapping',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Mapping'),
          'description' => E::ts('Entity Type'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_card_mapping.entity_mapping',
          'table_name' => 'civicrm_card_mapping',
          'entity' => 'Card',
          'bao' => 'CRM_Card_DAO_Card',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'card_mapping', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'card_mapping', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
